// 사이트 전체 콘텐츠. 서비스 소개로 바꿀 때 이 파일만 수정하면 됩니다.
// ornament: 제목에서 손글씨 장식을 겹칠 글자 인덱스 (0부터)
window.SITE = {
  brand: "Your Studio",
  intro: "You are diving into the world of<br>a small studio that makes<br>stories people remember.",
  subheading: "Explore Project & Extra Material",
  works: [
    { title: "Blue Horizon",     label: "Project: The Long Crossing",   img: "assets/img/work-01.webp", tone: "#2c45d8", ornament: [1, 6] },
    { title: "Paper Atelier",    label: "Project: Drafts by the Window", img: "assets/img/work-02.webp", tone: "#9a7a3c", ornament: [0, 9] },
    { title: "Neon Rain",        label: "Project: Umbrella Nights",     img: "assets/img/work-03.webp", tone: "#1f8f8f", ornament: [1] },
    { title: "Glasshouse",       label: "Project: Morning Mist",        img: "assets/img/work-04.webp", tone: "#2f7a4a", ornament: [0, 6] },
    { title: "Scarlet Stage",    label: "Project: The Last Spin",       img: "assets/img/work-05.webp", tone: "#a3182a", ornament: [8] },
    { title: "Starwatch",        label: "Project: First Light",         img: "assets/img/work-06.webp", tone: "#6b5aa6", ornament: [0, 4] },
    { title: "Paper Boats",      label: "Project: Down the Canal",      img: "assets/img/work-07.webp", tone: "#7f97b0", ornament: [7] },
    { title: "Side B Records",   label: "Project: Needle Drop",         img: "assets/img/work-08.webp", tone: "#b05a22", ornament: [0, 12] },
    { title: "Lantern",          label: "Project: Fireflies",           img: "assets/img/work-09.webp", tone: "#d8a02a", ornament: [1] },
    { title: "Open Road",        label: "Project: Golden Hour",         img: "assets/img/work-10.webp", tone: "#d29a6a", ornament: [0, 5] },
  ],
  news: [
    { title: "A new chapter begins", desc: "We're opening our doors to a handful of new partners this season. Here is what we are looking for and how to reach us.", cta: "Read more", img: "assets/img/work-06.webp" },
    { title: "Behind “Blue Horizon”", desc: "How a single sketch of a rowboat turned into our biggest project of the year.", cta: "Watch the story", img: "assets/img/work-01.webp" },
    { title: "Studio notes, Vol. 3", desc: "Process, mistakes and small wins from the last few months.", cta: "Read the notes", img: "assets/img/work-02.webp" },
    { title: "Join us on stage", desc: "We're hosting an open evening with talks, music and a few surprises.", cta: "Get tickets", img: "assets/img/work-05.webp" },
    { title: "Field recordings", desc: "A playlist of sounds collected while making “Neon Rain”.", cta: "Listen", img: "assets/img/work-03.webp" },
  ],
  story: [
    { nav: "Your Studio", years: "Summary", label: "Summary", title: "Our Story", ornament: [1, 6],
      lead: "Your Studio is a small team that turns ideas into experiences people want to come back to. This is a placeholder paragraph — replace it with a one-line description of your service.",
      body: "We work closely with a handful of partners each year, from first sketch to final launch. Use this space for a short supporting paragraph about how you work.",
      pieces: [{ img: "assets/img/story-06.webp", desc: "A caption for the image. Explain what the reader is looking at and why it matters to your story." }] },
    { nav: "Early Days", years: "2014 — 2016", label: "2014 — 2016", title: "Early Days", ornament: [1, 7],
      lead: "It started in a tiny room with one desk, a borrowed piano and far too many ideas. Replace this with how your service began.",
      body: "Talk about the problem you noticed first, and the people you built the first version for.",
      pieces: [{ img: "assets/img/story-01.webp", desc: "The first workspace. Every story needs a humble beginning." },
               { img: "assets/img/story-02.webp", desc: "Learning the craft — long nights in the studio with friends who became the founding team." }] },
    { nav: "First Office", years: "2017 — 2019", label: "2017 — 2019", title: "First Office", ornament: [0, 6],
      lead: "Two desks, a kettle and a wall of sticky notes became our first real office.",
      body: "Describe the first customers, the first wins and the lessons that shaped the way you work today.",
      pieces: [{ img: "assets/img/story-03.webp", desc: "Where most of our early projects were planned — usually after midnight." }] },
    { nav: "On Stage", years: "2020 — 2022", label: "2020 — 2022", title: "On Stage", ornament: [3],
      lead: "Our work moved from screens to stages, and we learned to build for live audiences.",
      body: "Share a turning point: a big launch, a new market or a product that changed everything.",
      pieces: [{ img: "assets/img/story-04.webp", desc: "Backstage before our first live show. Replace with a milestone photo of your own." }] },
    { nav: "Today", years: "2023 — Current", label: "2023 — Current", title: "Today", ornament: [0],
      lead: "Today we're a team of makers working with partners around the world.",
      body: "Close with where you are now and where you're heading next. Invite the reader to get in touch.",
      pieces: [{ img: "assets/img/story-05.webp", desc: "The studio as it is today — more people, the same curiosity." }] },
  ],
  faq: [
    { q: "What does Your Studio do?", a: "Replace this answer with a short, clear description of your service." },
    { q: "Who do you work with?", a: "Describe your ideal customers or partners here." },
    { q: "How long does a project take?", a: "Give a typical timeline and what affects it." },
    { q: "How do I get started?", a: "Explain the first step — a call, a form or an email address." },
  ],
};
